pull_request_rules:
  - name: Automatically merge Renovate PRs
    conditions:
      - author = renovate[bot]
      - check-success = spelling
      - check-success = ruff
      - check-success = pyright
      - check-success = pylint
      - check-success = scout
    actions:
      queue:
      label:
        add:
          - dependencies
queue_rules:
  - queue_branch_merge_method: fast-forward
    allow_queue_branch_edit: true
    update_method: merge
    name: default
