version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "python"
dependency_file_paths = ["requirements.txt", "pyproject.toml"]
[analyzers.meta]
runtime_version = "3.x.x"
type_checker = "mypy"

[[analyzers]]
name = "docker"

[[transformers]]
name = "ruff"

[[transformers]]
name = "isort"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "terraform"
enabled = true

