[package]
name = "voice_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
sherpa-rs = { version = "0.6.5", default-features = false, features = [
    "cuda",
    "tts",
] }
