[package]
name = "voice_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.8.3", features = ["cuda"] }
candle-nn = "0.8.3"
hf-hub = "0.4.1"
hound = "3.5.1"
tokenizers = "0.21.0"
