[project]
name = "vocalizr"
version = "0.0.1"
description = "Voice Generator part of the Chatacter Backend"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "en-core-web-sm",
    "gradio[mcp]>=5.29.0",
    "kokoro>=0.9.4",
    "soundfile>=0.13.1",
]

[project.scripts]
vocalizr = "vocalizr.__main__:main"

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "black>=25.1.0",
    "watchfiles>=1.0.5",
    "ruff>=0.11.10",
    "typos>=1.32.0",
    "pylint>=3.3.7",
    "pyright>=1.1.400",
    "huggingface-hub[cli,hf-transfer]>=0.31.2",
    "ty>=0.0.1a3",
]

[tool.typos.default.extend-words]
Chatacter = "Chatacter"

[tool.pylint]
disable = ["E1101", "C0114", "R0913", "R0917"]

[tool.ruff]
show-fixes = true

[tool.uv.sources]
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl" }
