[project]
name = "voice_generator"
version = "0.1.0"
description = "Voice Generator part of the Chatacter Backend"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.4.0",
    "fastapi[standard]>=0.115.8",
    "optimum>=1.24.0",
    "scipy>=1.15.2",
    "soundfile>=0.13.1",
    "transformers>=4.49.0",
]
