[project]
name = "voice-generator"
version = "0.1.0"
description = "Voice Generator part of the Chatacter Backend"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio[mcp]>=5.29.0",
    "kokoro>=0.9.4",
    "pip>=25.1.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
voice_generator = "voice_generator.__main__:main"

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pylint>=3.3.7",
    "pyrefly>=0.13.1",
    "ruff>=0.11.8",
    "typos>=1.32.0",
    "black>=25.1.0",
]

[tool.typos.default.extend-words]
Chatacter = "Chatacter"

[tool.pyrefly]
python_interpreter = ".venv/Scripts/python"

[tool.pylint]
disable = ["E1101"]
