[project]
name = "voice_generator"
version = "0.1.0"
description = "Voice Generator part of the Chatacter Backend"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.29.0",
    "kokoro>=0.9.4",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pyright>=1.1.400",
]
