[project]
name = "voice_generator"
version = "0.1.0"
description = "Voice Generator part of the Chatacter Backend"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate>=0.34.0",
    "fastapi[standard]>=0.112.2",
    "optimum>=1.17.1",
    "scipy>=1.14.1",
    "soundfile>=0.12.1",
    "transformers>=4.44.2",
]
