name: Push to HuggingFace
on:
  push:
jobs:
  Sync:
    runs-on: ubuntu-latest
    env:
      HF_HUB_ENABLE_HF_TRANSFER: 1
      UV_CACHE_DIR: /tmp/.uv-cache
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Restore uv cache
        uses: actions/cache@v4.2.3
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6.0.1
      - name: Install the huggingface cli
        run: uv tool install huggingface-hub[hf-transfer]
      - name: Remove Unnecessary Files
        run: |
          rm -rd .github
          rm -rd .idea
          rm docker-bake.hcl
          rm renovate.json
          rm .deepsource.toml
      - name: Add to git credentials
        run: git config --global credential.helper store
      - name: Login to HuggingFace Hub
        run: huggingface-cli login --add-to-git-credential --token ${{ secrets.HF_TOKEN }}
      - name: Check if logged in
        run: huggingface-cli whoami
      - name: Upload
        run: huggingface-cli upload AlphaSphereDotAI/Vocalizr . . --repo-type space
      - name: Minimize uv cache
        run: uv cache prune --ci
