name: Push to HuggingFace
on:
  push:
env:
  HF_HUB_ENABLE_HF_TRANSFER: 1
  UV_CACHE_DIR: /tmp/.uv-cache
jobs:
  export_requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - name: Setup UV
        uses: ./.github/actions/uv
      - name: Export
        run: uv export --no-hashes --no-editable --no-dev --quiet -o requirements.txt
      - name: Update file
        continue-on-error: true
        run: |
          git config --global user.email "mohamed.hisham.abdelzaher@gmail.com"
          git config --global user.name "Mohamed Hisham Abdelzaher"
          git add requirements.txt
          git commit -m "Update requirements.txt"
          git pull
          git push
      - name: Minimize uv cache
        run: uv cache prune --ci
  huggingface:
    needs: [export_requirements]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup UV
        uses: ./.github/actions/uv
      - name: Remove Unnecessary Files
        run: |
          rm -rd .github
          rm -rd .idea
          rm docker-bake.hcl
          rm renovate.json
          rm .deepsource.toml
      - name: Add to git credentials
        run: git config --global credential.helper store
      - name: Login to HuggingFace Hub
        run: uv run huggingface-cli login --add-to-git-credential --token ${{ secrets.HF_TOKEN }}
      - name: Check if logged in
        run: uv run huggingface-cli whoami
      - name: Upload
        run: uv run huggingface-cli upload AlphaSphereDotAI/Vocalizr . . --repo-type space
      - name: Minimize uv cache
        run: uv cache prune --ci
