name: Push to HuggingFace
on:
  push:
env:
  HF_HUB_ENABLE_HF_TRANSFER: 1
  UV_CACHE_DIR: /tmp/.uv-cache
jobs:
  huggingface:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup UV
        uses: ./.github/actions/uv
      - name: Remove Unnecessary Files
        run: |
          echo ".github" >> .gitignore
          echo ".idea" >> .gitignore
          echo "docker-bake.hcl" >> .gitignore
          echo "renovate.json" >> .gitignore
          echo ".deepsource.toml" >> .gitignore
      - name: Add to git credentials
        run: git config --global credential.helper store
      - name: Login to HuggingFace Hub
        run: uv run huggingface-cli login --add-to-git-credential --token ${{ secrets.HF_TOKEN }}
      - name: Check if logged in
        run: uv run huggingface-cli whoami
      - name: Upload
        run: uv run huggingface-cli upload AlphaSphereDotAI/Vocalizr . . --repo-type space
      - name: Minimize uv cache
        run: uv cache prune --ci
