name: Pylint
on:
  push:
  pull_request:
jobs:
  build:
    env:
      UV_CACHE_DIR: /tmp/.uv-cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4.2.2
      - name: Restore uv cache
        uses: actions/cache@v4.2.3
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6.0.1
      - name: Install the pylint
        run: uv tool install pylint
      - name: Analysing the code with Pylint
        run: pylint $(git ls-files '*.py') --output-format=github --rcfile pyproject.toml
      - name: Minimize uv cache
        run: uv cache prune --ci
