name: Pylint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.0.0
    - name: Install uv
      uses: astral-sh/setup-uv@v6.0.1
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    - name: Install the project
      run: uv sync --locked --all-extras --dev
    - name: Analysing the code with Pylint
      run: uv run pylint $(git ls-files '*.py') --output-format=colorized
