name: Requirements
on:
  push:
env:
  UV_CACHE_DIR: /tmp/.uv-cache
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - name: Setup UV
        uses: ./.github/actions/uv
      - name: Export
        run: uv export --no-hashes --no-editable --no-dev --quiet -o requirements.txt
      - name: Update file
        continue-on-error: true
        run: |
          git config --global user.email "mohamed.hisham.abdelzaher@gmail.com"
          git config --global user.name "Mohamed Hisham Abdelzaher"
          git add requirements.txt
          git commit -m "Update requirements.txt"
          git pull
          git push
      - name: Minimize uv cache
        run: uv cache prune --ci
