name: Requirements
on: push
jobs:
  build:
    env:
      UV_CACHE_DIR: /tmp/.uv-cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4.2.2
      - name: Restore uv cache
        uses: actions/cache@v4.2.3
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6.0.1
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Export
        run: uv export --no-hashes --no-editable --no-dev -o requirements.txt
      - name: Update file
        continue-on-error: true
        run: |
          git add requirements.txt
          git commit -m "Update requirements.txt"
          git pull
          git push