name: Spelling
on: [pull_request, push]
permissions:
  contents: read
env:
  CLICOLOR: 1
jobs:
  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4.2.2
      - name: Install uv
        uses: astral-sh/setup-uv@v6.0.1
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Run typos
        run: uv run typos . --config ./pyproject.toml