name: Spelling
on: [ pull_request, push ]
jobs:
  spelling:
    name: Spell Check with Typos
    env:
      UV_CACHE_DIR: /tmp/.uv-cache
      CLICOLOR: 1
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4.2.2
      - name: Restore uv cache
        uses: actions/cache@v4.2.3
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6.0.1
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Run typos
        run: uv run typos . --config ./pyproject.toml